// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hidvfdmagncfnlnhtyda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpZHZmZG1hZ25jZm5sbmh0eWRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTQxOTEsImV4cCI6MjA2NTU3MDE5MX0.ga--zr1KTCQRNZy1G8GEmLIrlwITCpTVatdi93GVEwk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);